root:
  clk:
    frequency_hz: 25000
    initial_phase: 0
  clk_cmd_handler:
    frequency_hz: 100000.0
    initial_phase: 0
  clk_fast:
    frequency_hz: 100000.0
    initial_phase: 0
  clk_slow:
    frequency_hz: 25000.0
    initial_phase: 0
  enable_log: 0
  logger_max_buffer_size: 1000
  n_iterations: 10000
  n_ovr: 4
  u_parallel_filter:
    coeffs: 0.25,0.25,0.25,0.25
  u_symbol_gen:
    seed: 0
  u_upsampler:
    phase: 0
